version: "3.9"

services:
  # PSSQL
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwe321
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    environment: 
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080    